server:
  servlet:
    context-path: /restaurante-delivery/api

spring:
  data:
    mongodb:
      authentication-database: admin
      uri: ${MONGO_DB_URI:mongodb+srv://neramornas:DpXb9U1fYmFTgluY@wakanda.d3o3yvu.mongodb.net/?retryWrites=true&w=majority&appName=Wakanda}
      auto-index-creation: true
  main:
    allow-circular-references: true

api:
  security:
    token:
      secret: ${JWT_SECRET:DLPI21D9ITPLAS}

springdoc:
  swagger-ui:
    path: /swagger-ui