server:
 servlet:
    context-path: /restaurante-delivery/api
    
spring:
  data:
    mongodb:
      authentication-database: admin
      uri: ${MONGO_DB_URI:mongodb+srv://neramornas:JtFWUAGW1HZoMw1d@wakanda.d3o3yvu.mongodb.net/?retryWrites=true&w=majority&appName=Wakanda}
      auto-index-creation: true
      database: restaurante-delivery
  

springdoc:
  swagger-ui:
    path: /swagger-ui      
